install: ssh_ssl_proxy
	gksudo "../scripts/install.sh install $$PWD"
	  
uninstall:
	gksudo "../scripts/install.sh uninstall"
	
make_deb: ssh_ssl_proxy
	gksudo "/bin/bash -x ../scripts/install.sh make_deb $$PWD"
	  